# mongo -> json-server -> repair -> seg-tool
version: "2"
services:
  seg-tool:
    container_name: seg-tool
    #volumes:
    #  - ./imgs:/src/imgs_vid1
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    image: seg-tool
    ports:
      - "5000:3000"
    depends_on:
      - mongo-server
      - json-server
    links:
      - mongo-server
      - json-server
    volumes:
      - ./backup:/server/backup

  json-server:
    container_name: json-server
    image: json-server
    restart: always
    build: ./server
    ports:
      - "3001:3001"
    links:
      - mongo-server

  # mongo:
  #   container_name: mongo
  #   image: mongo
  #   # volumes:
  #   #   - ./data:/data/db
  #   # ports:
  #   #   - "27017:27017"

  mongo-server:
    container_name: mongo-server
    image: mongo-server
    restart: always
    build: ./repair