version: "2"
services:
  app:
    container_name: seg-tool
    restart: always
    build: .
    ports:
      - "5000:5000"
    links:
      - mongo
  json-server:
    container_name: json-server
    restart: always
    build: ./server
    ports:
      - "3001:3001"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"