#!/bin/bash

#docker-compose up &

# Get the image id
id1="$(docker images | grep seg-tool | awk '{print $3}')"
id2="$(docker images | grep json-server | awk '{print $3}')"
id3="$(docker images | grep mongo-server | awk '{print $3}')"

# Save the files
docker save -o seg-tool.tar.gz $id1 
docker save -o json-server.tar.gz $id2
docker save -o mongo-server.tar.gz $id3